language: node_js
node_js:
  - "10"
sudo: required
install: echo "Begin install"
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.08
os:
  - linux
cache:
  directories:
    - $HOME/.opam
    - $HOME/.esy
  
